### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by errorline99**
I enlarged the Github and LinkedIn icons like you asked

### CODE REVIEW

**Comment by thedtripp** [comment]
Thanks for working on this.
I didn't realize that people other than myself would contribute to this and I should have been more specific.
I'd like for the GitHub and LinkedIn buttons to be approximately equal in height to the resume button.
I'd also like for the spacing between the three items to approximately equal.
Thank you.

**Comment by errorline99** [comment]
done, hope this looks fit.
please inform me if something looks out of place

**Review by thedtripp — CHANGES_REQUESTED** [review]
Looks better. 
I have a fix for the spacing.
Please just set the font size to 2.8rem, and remove the margin 10px.
Then, I'll approve the PR.

**Review by thedtripp — APPROVED** [review]
Great work. :)

**Comment by errorline99** [comment]
thanks

**Pull request merged**
